version: '3'

services:
  statsd-http-proxy:
    container_name: ${CONTAINER_NAME:-statsd-http-proxy}
    build: .
    ports:
      - "${HTTP_PORT:-8825}:8825"
    restart: unless-stopped
    read_only: true
    environment:
      VERBOSE: ${VERBOSE:-true}
      HTTP_PORT: ${HTTP_PORT:-8825}
      JWT_SECRET: ${JWT_SECRET:-}
      # JWT_SECRET: "whatever"
      STATSD_HOST: ${STATSD_HOST:-127.0.0.1}
      STATSD_PORT: ${STATSD_PORT:-8125}

