name: Deploy Images to GHCR and Docker Hub

env:
  USER: dominikborkowski
  PROJECT: statsd-http-proxy
  VERSION: 1.0.0

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.USER }}/${{ env.PROJECT }}:latest
            ghcr.io/${{ env.USER }}/${{ env.PROJECT }}:${{ env.VERSION }}
            ${{ env.USER }}/${{ env.PROJECT }}:latest
            ${{ env.USER }}/${{ env.PROJECT }}:${{ env.VERSION }}

